language: ruby

rvm: 
 - 2.5.0

bundler_args: "--without development --deployment"

cache: bundler

install:
  - gem install -v 1.16.1 bundler
  - bundle install
  - npm install

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  - npm run lint
  - bin/rails test
  - bin/rails spec
  - bin/bundle exec brakeman -z -A --except CheckUnscopedFind -w1
