env:
  global:
    - CC_TEST_REPORTER_ID=caafaf988393467d4e549b54331511085b9817212ee864e4f3db01c8d9dfa648

language: ruby

rvm: 
  - 2.5.3

bundler_args: "--without development --deployment"

cache: bundler

before_install:
  - gem update --system --no-document

install:
  - bundle install
  - yarn install

before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/google_api.yml.sample config/google_api.yml
  - bin/bundle exec rake db:create
  - bin/bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn lint
  - bin/rails test
  - bin/rspec --tag ~google_api
  - bin/bundle exec brakeman -z -A -w1

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
